### ISSUE TITLE
Testes unitários

### ISSUE THREAD

**Issue by rafaelcanovas** [Luanafrtd/project-anima-vita#1]
https://github.com/Luanafrtd/project-anima-vita/blob/300d08f642e3c736827159ce05221e51407ccee4/src/App.test.tsx#L5-L9

Boa tarde Luana, tudo bem?

Ao rodar os testes da aplicação percebi que esse teste está falhando.

Na sua opinião, qual a importância dos testes unitários para uma aplicação frontend, e quais são os outros tipos de testes que podem empregar para garantir a qualidade da aplicação.

Obrigado!

**Comment by Luanafrtd** [comment]
Rafa, eu não tenho muita experiência com testes unitários. Sei que servem para irmos agregando novas funcionalidades aos nossos projetos garantindo o funcionamento de funcionalidades mais antigas. Sei também que são muito úteis em determinadas refatorações. As duas bibliotecas de testes mais famosas para testes unitários de componentes são enzyme e react-testing-library (RTL) e estávamos para começar a testar as aplicações onde eu trabalhava antes usando o RTL, mas acabou que não cheguei a trabalhar com.
O motivo do teste não estar funcionando é que ele está procurando um elemento através do texto learn react, texto esse que vem por padrão em uma aplicação CRA. Eu removi esse texto para a criação da pagina de animes.

**Comment by rafaelcanovas** [comment]
Muito obrigado pela resposta Luana!
