### ISSUE TITLE
Telas e componentes da aplicação

### ISSUE THREAD

**Issue by rafaelcanovas** [Luanafrtd/project-anima-vita#2]
https://github.com/Luanafrtd/project-anima-vita/blob/300d08f642e3c736827159ce05221e51407ccee4/src/App.tsx#L18-L62

Boa noite Luana, tudo bem?

Percebi que escolheu abrigar a única tela da aplicação no componente raiz da aplicação `App`. Isto funciona por se tratar de uma aplicação muito pequena.

Como você enxergaria o crescimento da aplicação, quando surgirem novas telas, componentes, como seria a melhor forma de organizar isso?

Obrigado.

**Comment by Luanafrtd** [comment]
Boa tarde Rafa!
A aplicação demanda ranqueamento nos principais mecanismos de busca? Se sim, eu indicaria usarmos Next.js que já contempla essa questão do roteamento através do uso do diretório pages. Caso contrário, indicaria organizarmos as rotas em um arquivo específico usando react router. Se o projeto for pequeno podemos organizar as rotas no próprio App.js.

**Comment by rafaelcanovas** [comment]
Muito obrigado pela resposta Luana!
