### ISSUE TITLE
devDependencies

### ISSUE THREAD

**Issue by rafaelcanovas** [Luanafrtd/project-anima-vita#3]
https://github.com/Luanafrtd/project-anima-vita/blob/300d08f642e3c736827159ce05221e51407ccee4/package.json#L45

Boa noite Luana, tudo bem?

Percebi que escolheu manter apenas uma das bibliotecas de tipos nas `devDependencies`. Qual a importância desta propriedade, qual seu impacto final na aplicação e por que escolheu manter apenas esta biblioteca na `devDependencies`?

Muito obrigado!

**Comment by Luanafrtd** [comment]
Rafa, eu criei está aplicação usando CRA --template typescript, acabou vindo organizado dessa maneira e esqueci de dar uma conferida. A única dependência que instalei foi a de tipos do styled-componets, a qual tive o cuidado de deixar como dependência de desenvolvimento. 
A importância do devDependencies é a de separar do build dependências que são úteis apenas no desenvolvimento da aplicação. Excluir essas dependências inúteis para a execução do projeto torna o build mais compacto.

**Comment by rafaelcanovas** [comment]
Muito obrigado pela resposta Luana!
